name: ${project.name}
description: ${project.description}
main: org.retromc.retrobridge.RetroBridge
version: ${project.version}
authors:
  - JohnyMuffin

load: STARTUP # Load before most plugins

commands:
  retrobridge:
    description: RetroBridge command set.
    usage: /<command> [status]
    permission: retrobridge.status

permissions:
  retrobridge.status:
    description: Allows viewing RetroBridge active provider status.
    default: op
